# customer churn prediction

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
import warnings
warnings.filterwarnings("ignore")

In [3]:
path=r"C:\Users\hansh\OneDrive\Documents\customer_churn (1).csv"
df=pd.read_csv(path)
df

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [4]:
# data cleaning
df.drop("customerID",axis=1,inplace=True)
df

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,No,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.5,No
7039,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,Yes,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.9,No
7040,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,No,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.6,Yes
7042,Male,0,No,No,66,Yes,No,Fiber optic,Yes,No,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.5,No

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gender            7043 non-null   object
 1   SeniorCitizen     7043 non-null   int64
 2   Partner           7043 non-null   object
 3   Dependents        7043 non-null   object
 4   tenure            7043 non-null   int64
 5   PhoneService      7043 non-null   object
 6   MultipleLines     7043 non-null   object
 7   InternetService   7043 non-null   object
 8   OnlineSecurity    7043 non-null   object
 9   OnlineBackup      7043 non-null   object
 10  DeviceProtection  7043 non-null   object
 11  TechSupport       7043 non-null   object
 12  StreamingTV       7043 non-null   object
 13  StreamingMovies   7043 non-null   object
 14  Contract          7043 non-null   object
 15  PaperlessBilling  7043 non-null   object
 16  PaymentMethod     7043 non-null   object
 17  MonthlyCharges    7043 non-null   float64
 18  TotalCharges      7043 non-null   object
 19  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(17)
memory usage: 1.1+ MB

In [6]:
df.drop_duplicates(inplace=True)

In [7]:
df.shape

(7021, 20)

In [8]:
df.isnull().sum()

gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [10]:
df.columns

Index(['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure',
       'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity',
       'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod',
       'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')

In [12]:
for i in df.columns:
    if df[i].dtype=="object":
        print(i)
        print(df[i].unique())

gender
['Female' 'Male']
Partner
['Yes' 'No']
Dependents
['No' 'Yes']
PhoneService
['No' 'Yes']
MultipleLines
['No phone service' 'No' 'Yes']
InternetService
['DSL' 'Fiber optic' 'No']
OnlineSecurity
['No' 'Yes' 'No internet service']
OnlineBackup
['Yes' 'No' 'No internet service']
DeviceProtection
['No' 'Yes' 'No internet service']
TechSupport
['No' 'Yes' 'No internet service']
StreamingTV
['No' 'Yes' 'No internet service']
StreamingMovies
['No' 'Yes' 'No internet service']
Contract
['Month-to-month' 'One year' 'Two year']
PaperlessBilling
['Yes' 'No']
PaymentMethod
['Electronic check' 'Mailed check' 'Bank transfer (automatic)'
 'Credit card (automatic)']
TotalCharges
['29.85' '1889.5' '108.15' ... '346.45' '306.6' '6844.5']
Churn
['No' 'Yes']

In [13]:
columns=["MultipleLines","OnlineSecurity","OnlineBackup","DeviceProtection","TechSupport","StreamingTV","StreamingMovies"]

In [15]:
for i in columns:
    df[i]=df[i].apply(lambda i:"No" if i=="No internet service" else i)

In [16]:
for i in df.columns:
    if df[i].dtype=="object":
        print(i)
        print(df[i].unique())

gender
['Female' 'Male']
Partner
['Yes' 'No']
Dependents
['No' 'Yes']
PhoneService
['No' 'Yes']
MultipleLines
['No phone service' 'No' 'Yes']
InternetService
['DSL' 'Fiber optic' 'No']
OnlineSecurity
['No' 'Yes']
OnlineBackup
['Yes' 'No']
DeviceProtection
['No' 'Yes']
TechSupport
['No' 'Yes']
StreamingTV
['No' 'Yes']
StreamingMovies
['No' 'Yes']
Contract
['Month-to-month' 'One year' 'Two year']
PaperlessBilling
['Yes' 'No']
PaymentMethod
['Electronic check' 'Mailed check' 'Bank transfer (automatic)'
 'Credit card (automatic)']
TotalCharges
['29.85' '1889.5' '108.15' ... '346.45' '306.6' '6844.5']
Churn
['No' 'Yes']

In [17]:
df["MultipleLines"]=df["MultipleLines"].apply(lambda i:"No" if i=='No phone service' else i)

In [18]:
for i in df.columns:
    if df[i].dtype=="object":
        print(i)
        print(df[i].unique())

gender
['Female' 'Male']
Partner
['Yes' 'No']
Dependents
['No' 'Yes']
PhoneService
['No' 'Yes']
MultipleLines
['No' 'Yes']
InternetService
['DSL' 'Fiber optic' 'No']
OnlineSecurity
['No' 'Yes']
OnlineBackup
['Yes' 'No']
DeviceProtection
['No' 'Yes']
TechSupport
['No' 'Yes']
StreamingTV
['No' 'Yes']
StreamingMovies
['No' 'Yes']
Contract
['Month-to-month' 'One year' 'Two year']
PaperlessBilling
['Yes' 'No']
PaymentMethod
['Electronic check' 'Mailed check' 'Bank transfer (automatic)'
 'Credit card (automatic)']
TotalCharges
['29.85' '1889.5' '108.15' ... '346.45' '306.6' '6844.5']
Churn
['No' 'Yes']

In [19]:
df["gender"]=df["gender"].map({"Female":0,"Male":1})

In [20]:
for i in df.columns:
    if df[i].dtype=="object":
        print(i)
        print(df[i].unique())

Partner
['Yes' 'No']
Dependents
['No' 'Yes']
PhoneService
['No' 'Yes']
MultipleLines
['No' 'Yes']
InternetService
['DSL' 'Fiber optic' 'No']
OnlineSecurity
['No' 'Yes']
OnlineBackup
['Yes' 'No']
DeviceProtection
['No' 'Yes']
TechSupport
['No' 'Yes']
StreamingTV
['No' 'Yes']
StreamingMovies
['No' 'Yes']
Contract
['Month-to-month' 'One year' 'Two year']
PaperlessBilling
['Yes' 'No']
PaymentMethod
['Electronic check' 'Mailed check' 'Bank transfer (automatic)'
 'Credit card (automatic)']
TotalCharges
['29.85' '1889.5' '108.15' ... '346.45' '306.6' '6844.5']
Churn
['No' 'Yes']

In [21]:
df.columns

Index(['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure',
       'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity',
       'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod',
       'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')

In [22]:
col=['Partner', 'Dependents',
       'PhoneService', 'MultipleLines', 'OnlineSecurity',
       'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies','PaperlessBilling', 'Churn']

In [23]:
for i in col:
    print(i)
    print(df[i].unique())

Partner
['Yes' 'No']
Dependents
['No' 'Yes']
PhoneService
['No' 'Yes']
MultipleLines
['No' 'Yes']
OnlineSecurity
['No' 'Yes']
OnlineBackup
['Yes' 'No']
DeviceProtection
['No' 'Yes']
TechSupport
['No' 'Yes']
StreamingTV
['No' 'Yes']
StreamingMovies
['No' 'Yes']
PaperlessBilling
['Yes' 'No']
Churn
['No' 'Yes']

In [24]:
for i in col:
    df[i]=df[i].apply(lambda i:0 if i=='No' else 1)

In [25]:
for i in df.columns:
    if df[i].dtype=="object":
        print(i)
        print(df[i].unique())

InternetService
['DSL' 'Fiber optic' 'No']
Contract
['Month-to-month' 'One year' 'Two year']
PaymentMethod
['Electronic check' 'Mailed check' 'Bank transfer (automatic)'
 'Credit card (automatic)']
TotalCharges
['29.85' '1889.5' '108.15' ... '346.45' '306.6' '6844.5']

In [26]:
df["InternetService"]=df["InternetService"].map({'DSL':1, 'Fiber optic':2, 'No':0})

In [27]:
df["Contract"]=df["Contract"].map({'Month-to-month':0, 'One year':1, 'Two year':2})

In [28]:
df["PaymentMethod"]=df["PaymentMethod"].map({'Electronic check':1,'Mailed check':0,
                                             'Bank transfer (automatic)':2,
 'Credit card (automatic)':3})

In [29]:
for i in df.columns:
    if df[i].dtype=="object":
        print(i)
        print(df[i].unique())

TotalCharges
['29.85' '1889.5' '108.15' ... '346.45' '306.6' '6844.5']

In [30]:
df1=df[~(df.TotalCharges==" ")]
df1

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,0,0,1,0,1,0,0,1,0,1,0,0,0,0,0,1,1,29.85,29.85,0
1,1,0,0,0,34,1,0,1,1,0,1,0,0,0,1,0,0,56.95,1889.5,0
2,1,0,0,0,2,1,0,1,1,1,0,0,0,0,0,1,0,53.85,108.15,1
3,1,0,0,0,45,0,0,1,1,0,1,1,0,0,1,0,2,42.30,1840.75,0
4,0,0,0,0,2,1,0,2,0,0,0,0,0,0,0,1,1,70.70,151.65,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,1,0,1,1,24,1,1,1,1,0,1,1,1,1,1,1,0,84.80,1990.5,0
7039,0,0,1,1,72,1,1,2,0,1,1,0,1,1,1,1,3,103.20,7362.9,0
7040,0,0,1,1,11,0,0,1,1,0,0,0,0,0,0,1,1,29.60,346.45,0
7041,1,1,1,0,4,1,1,2,0,0,0,0,0,0,0,1,0,74.40,306.6,1
7042,1,0,0,0,66,1,0,2,1,0,1,1,1,1,2,1,2,105.65,6844.5,0

In [31]:
df1["TotalCharges"]=df1["TotalCharges"].apply(lambda i:float(i))

In [32]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7010 entries, 0 to 7042
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   gender            7010 non-null   int64
 1   SeniorCitizen     7010 non-null   int64
 2   Partner           7010 non-null   int64
 3   Dependents        7010 non-null   int64
 4   tenure            7010 non-null   int64
 5   PhoneService      7010 non-null   int64
 6   MultipleLines     7010 non-null   int64
 7   InternetService   7010 non-null   int64
 8   OnlineSecurity    7010 non-null   int64
 9   OnlineBackup      7010 non-null   int64
 10  DeviceProtection  7010 non-null   int64
 11  TechSupport       7010 non-null   int64
 12  StreamingTV       7010 non-null   int64
 13  StreamingMovies   7010 non-null   int64
 14  Contract          7010 non-null   int64
 15  PaperlessBilling  7010 non-null   int64
 16  PaymentMethod     7010 non-null   int64
 17  MonthlyCharges    7010 non-null   float64
 18  TotalCharges      7010 non-null   float64
 19  Churn             7010 non-null   int64
dtypes: float64(2), int64(18)
memory usage: 1.1 MB

In [33]:
# input and output
#input
x=df1.drop("Churn",axis=1)
x

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges
0,0,0,1,0,1,0,0,1,0,1,0,0,0,0,0,1,1,29.85,29.85
1,1,0,0,0,34,1,0,1,1,0,1,0,0,0,1,0,0,56.95,1889.50
2,1,0,0,0,2,1,0,1,1,1,0,0,0,0,0,1,0,53.85,108.15
3,1,0,0,0,45,0,0,1,1,0,1,1,0,0,1,0,2,42.30,1840.75
4,0,0,0,0,2,1,0,2,0,0,0,0,0,0,0,1,1,70.70,151.65
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,1,0,1,1,24,1,1,1,1,0,1,1,1,1,1,1,0,84.80,1990.50
7039,0,0,1,1,72,1,1,2,0,1,1,0,1,1,1,1,3,103.20,7362.90
7040,0,0,1,1,11,0,0,1,1,0,0,0,0,0,0,1,1,29.60,346.45
7041,1,1,1,0,4,1,1,2,0,0,0,0,0,0,0,1,0,74.40,306.60
7042,1,0,0,0,66,1,0,2,1,0,1,1,1,1,2,1,2,105.65,6844.50

In [34]:
# output
y=df1.Churn
y

0       0
1       0
2       1
3       0
4       1
       ..
7038    0
7039    0
7040    0
7041    1
7042    0
Name: Churn, Length: 7010, dtype: int64

In [35]:
# train_test_split
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [36]:
print("shape of x_train=",x_train.shape)
print("shape of y_train=",y_train.shape)
print("shape of x_test=",x_test.shape)
print("shape of y_test=",y_test.shape)

shape of x_train= (5608, 19)
shape of y_train= (5608,)
shape of x_test= (1402, 19)
shape of y_test= (1402,)

In [37]:
# apply random forest classifier
from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier(n_estimators=100)
model.fit(x_train,y_train)

RandomForestClassifier()

In [38]:
# model score
model.score(x_test,y_test)*100

81.16975748930099

In [39]:
# prediction using model
prediction=model.predict(x_test)
prediction[:20]

array([0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0])

In [40]:
y_test.head(20)

6882    0
6752    0
245     0
1889    0
6830    0
3135    1
5997    0
3878    0
2717    0
2792    0
101     0
2398    0
2527    1
1679    0
2278    0
7013    0
3443    0
4193    0
1453    0
2188    0
Name: Churn, dtype: int64

In [41]:
# n_estimators=300
from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier(n_estimators=200)
model.fit(x_train,y_train)

RandomForestClassifier(n_estimators=200)

In [42]:
model.score(x_test,y_test)*100

81.09843081312411

In [43]:
# min_max_scaling
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
x_train_scaled=scaler.fit_transform(x_train)
x_train_scaled

array([[0.        , 0.        , 1.        , ..., 0.33333333, 0.35820896,
        0.13878952],
       [1.        , 0.        , 0.        , ..., 0.33333333, 0.36865672,
        0.01036811],
       [1.        , 0.        , 0.        , ..., 1.        , 0.17661692,
        0.15740826],
       ...,
       [0.        , 0.        , 0.        , ..., 0.33333333, 0.6119403 ,
        0.01681283],
       [0.        , 0.        , 1.        , ..., 0.66666667, 0.80348259,
        0.73355643],
       [1.        , 1.        , 1.        , ..., 0.33333333, 0.55124378,
        0.16670898]], shape=(5608, 19))

In [44]:
x_test_scaled=scaler.fit_transform(x_test)
x_test_scaled

array([[0.        , 1.        , 0.        , ..., 1.        , 0.81262525,
        0.84768651],
       [0.        , 0.        , 0.        , ..., 0.        , 0.31362725,
        0.06311136],
       [1.        , 1.        , 0.        , ..., 0.33333333, 0.56913828,
        0.03012658],
       ...,
       [1.        , 0.        , 0.        , ..., 0.33333333, 0.58016032,
        0.13003367],
       [0.        , 0.        , 1.        , ..., 0.66666667, 0.69539078,
        0.75112287],
       [0.        , 0.        , 1.        , ..., 0.33333333, 0.60721443,
        0.29736607]], shape=(1402, 19))

In [45]:
from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier(n_estimators=100)
model.fit(x_train_scaled,y_train)

RandomForestClassifier()

In [46]:
model.score(x_test_scaled,y_test)*100

80.95577746077034

In [47]:
#standard scaler
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
x_train_scaled=scaler.fit_transform(x_train)
x_train_scaled

array([[-1.00931586, -0.44702219,  1.03152374, ..., -0.39888612,
        -0.35913606, -0.46650494],
       [ 0.99077013, -0.44702219, -0.96943964, ..., -0.39888612,
        -0.32412198, -0.95856038],
       [ 0.99077013, -0.44702219, -0.96943964, ...,  1.48645172,
        -0.96771417, -0.39516597],
       ...,
       [-1.00931586, -0.44702219, -0.96943964, ..., -0.39888612,
         0.49120594, -0.93386697],
       [-1.00931586, -0.44702219,  1.03152374, ...,  0.5437828 ,
         1.13313079,  1.8123851 ],
       [ 0.99077013,  2.2370254 ,  1.03152374, ..., -0.39888612,
         0.2877908 , -0.35952964]], shape=(5608, 19))

In [48]:
x_test_scaled=scaler.fit_transform(x_test)
x_test_scaled

array([[-1.00572251,  2.40269575, -0.9649505 , ...,  1.44622129,
         1.16247593,  2.11607752],
       [-1.00572251, -0.41619918, -0.9649505 , ..., -1.34277767,
        -0.47817061, -0.78454715],
       [ 0.99431005,  2.40269575, -0.9649505 , ..., -0.41311135,
         0.36191949, -0.90649402],
       ...,
       [ 0.99431005, -0.41619918, -0.9649505 , ..., -0.41311135,
         0.39815867, -0.53713109],
       [-1.00572251, -0.41619918,  1.03632258, ...,  0.51655497,
         0.77702283,  1.75907554],
       [-1.00572251, -0.41619918,  1.03632258, ..., -0.41311135,
         0.48710938,  0.08150753]], shape=(1402, 19))

In [49]:
from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier(n_estimators=100)
model.fit(x_train_scaled,y_train)

RandomForestClassifier()

In [50]:
model.score(x_test_scaled,y_test)*100

80.09985734664765